---

- name: Download etcd-{{ etcd_version }}-linux-amd64.tar.gz
  get_url: url=https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz dest=/tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz

- name: Extract etcd-{{ etcd_version }}-linux-amd64.tar.gz
  unarchive: src=/tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz dest=/tmp remote_src=yes

- name: Copy etcd bin file to /usr/local/bin
  copy: src=/tmp/etcd-{{ etcd_version }}-linux-amd64/etcd dest=/usr/local/bin remote_src=yes

- name: Copy etcdctl bin file to /usr/local/bin
  copy: src=/tmp/etcd-{{ etcd_version }}-linux-amd64/etcdctl dest=/usr/local/bin remote_src=yes

- name: chmod +x etcd
  file: path=/usr/local/bin/etcd mode=755

- name: chmod +x etcdctl
  file: path=/usr/local/bin/etcdctl mode=755

- name: Create etcd data dir
  file: path={{ etcd_data_dir }} state=directory

- name: Create etcd service {{ inventory_hostname }}
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service force=yes

- name: Start etcd daemon
  systemd: name=etcd.service daemon_reload=yes state=started enabled=yes
